/**
 * Base Pet Seed Data - Extended Families
 * Families 5-10 (SHADOW_VEIL, LUMINA, STEEL_WORKS, ARCANE_RIFT, AERO_FLIGHT, WEIRDOS)
 * Generated from docs/CONTENT/PET_DESIGNS.md
 */

import { PetFamily } from '@/shared/types/family';
import { Rarity } from '@/shared/types/rarity';
import type { BasePet } from '@/domain/entities/BasePet';
import { brandBasePetId } from '@/shared/types/brands';

// SHADOW_VEIL - Shadow family (15 pets)
export const SHADOW_VEIL_PETS: BasePet[] = [
  // Basic
  {
    id: brandBasePetId('BASE-SHADOW-001'),
    name: 'Shadowling',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.BASIC,
    baseStats: { hp: 520, attack: 49, defense: 36, speed: 69 },
    starterAbilities: ['shadow-strike'],
    starterPassives: [],
    visualTags: ['shadow', 'dark', 'swift'],
    lore: 'A creature made of living shadows that can hide in any darkness.',
  },
  {
    id: brandBasePetId('BASE-SHADOW-002'),
    name: 'Nightwhisper',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.BASIC,
    baseStats: { hp: 535, attack: 48, defense: 37, speed: 70 },
    starterAbilities: ['whisper-curse'],
    starterPassives: [],
    visualTags: ['shadow', 'ethereal', 'mysterious'],
    lore: 'A being that speaks in shadows, its voice carrying dark intentions.',
  },
  {
    id: brandBasePetId('BASE-SHADOW-003'),
    name: 'Voidcrawler',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.BASIC,
    baseStats: { hp: 545, attack: 50, defense: 38, speed: 67 },
    starterAbilities: ['void-drain'],
    starterPassives: [],
    visualTags: ['shadow', 'crawling', 'absorbing'],
    lore: 'A creature that crawls through the void between worlds, draining energy.',
  },
  {
    id: brandBasePetId('BASE-SHADOW-004'),
    name: 'Nightreaper',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.BASIC,
    baseStats: { hp: 515, attack: 51, defense: 35, speed: 72 },
    starterAbilities: ['reaper-scythe'],
    starterPassives: [],
    visualTags: ['shadow', 'death', 'dark-harvest'],
    lore: 'A shadow spirit that collects the darkness from fallen things.',
  },
  {
    id: brandBasePetId('BASE-SHADOW-005'),
    name: 'Abyssling',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.BASIC,
    baseStats: { hp: 540, attack: 47, defense: 39, speed: 68 },
    starterAbilities: ['abyss-sink'],
    starterPassives: [],
    visualTags: ['shadow', 'deep', 'pulling'],
    lore: 'A tiny piece of the abyss given form, pulling things into eternal darkness.',
  },
  // Rare
  {
    id: brandBasePetId('BASE-SHADOW-006'),
    name: 'Darkwraith',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.RARE,
    baseStats: { hp: 900, attack: 85, defense: 63, speed: 76 },
    starterAbilities: ['shadow-bolt'],
    starterPassives: ['shadow-veil'],
    visualTags: ['shadow', 'ghost', 'powerful'],
    lore: 'A wraith of pure shadow that haunts The Grid, seeking to engulf all in darkness.',
  },
  {
    id: brandBasePetId('BASE-SHADOW-007'),
    name: 'Nightbane',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.RARE,
    baseStats: { hp: 920, attack: 87, defense: 65, speed: 74 },
    starterAbilities: ['bane-strike'],
    starterPassives: ['decay-aura'],
    visualTags: ['shadow', 'curse', 'malevolent'],
    lore: 'A curse given form, bringing ruin and decay to all it touches.',
  },
  {
    id: brandBasePetId('BASE-SHADOW-008'),
    name: 'Void Monarch',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.RARE,
    baseStats: { hp: 940, attack: 83, defense: 67, speed: 75 },
    starterAbilities: ['void-command'],
    starterPassives: ['shadow-master'],
    visualTags: ['shadow', 'royalty', 'commanding'],
    lore: 'A creature that rules the void between worlds with absolute authority.',
  },
  // SR
  {
    id: brandBasePetId('BASE-SHADOW-009'),
    name: 'Eclipse Dragon',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.SR,
    baseStats: { hp: 1510, attack: 132, defense: 106, speed: 86 },
    starterAbilities: ['eclipse-fury'],
    starterPassives: ['shadow-veil', 'decay-aura'],
    visualTags: ['shadow', 'dragon', 'eclipse'],
    lore: 'A dragon born from the shadow of a dying world, embodying eternal darkness.',
  },
  {
    id: brandBasePetId('BASE-SHADOW-010'),
    name: 'Deathbringer',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.SR,
    baseStats: { hp: 1490, attack: 135, defense: 104, speed: 88 },
    starterAbilities: ['death-touch'],
    starterPassives: ['shadow-master', 'decay-aura'],
    visualTags: ['shadow', 'death', 'reaper'],
    lore: 'A being that brings death and decay wherever it treads, ending all it encounters.',
  },
  {
    id: brandBasePetId('BASE-SHADOW-011'),
    name: 'Nightmare Hydra',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.SR,
    baseStats: { hp: 1540, attack: 130, defense: 108, speed: 84 },
    starterAbilities: ['nightmare-swarm'],
    starterPassives: ['shadow-veil', 'shadow-master'],
    visualTags: ['shadow', 'hydra', 'many-headed'],
    lore: 'A hydra of nightmares with infinite heads, each one darker than the last.',
  },
  // Legendary
  {
    id: brandBasePetId('BASE-SHADOW-012'),
    name: 'Hades Incarnate',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.LEGENDARY,
    baseStats: { hp: 2400, attack: 195, defense: 170, speed: 90 },
    starterAbilities: ['hades-judgment'],
    starterPassives: ['shadow-veil', 'decay-aura', 'shadow-master'],
    visualTags: ['shadow', 'god', 'underworld'],
    lore: 'The dark god of the underworld, judge of all souls, wielder of absolute shadow power.',
  },
  {
    id: brandBasePetId('BASE-SHADOW-013'),
    name: 'Void Devourer',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.LEGENDARY,
    baseStats: { hp: 2350, attack: 200, defense: 165, speed: 92 },
    starterAbilities: ['void-consume'],
    starterPassives: ['shadow-master', 'decay-aura', 'shadow-veil'],
    visualTags: ['shadow', 'devourer', 'cosmic'],
    lore: 'A creature from beyond reality that devours light, matter, and existence itself.',
  },
  // Mythic
  {
    id: brandBasePetId('BASE-SHADOW-014'),
    name: 'Eternal Night',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.MYTHIC,
    baseStats: { hp: 3850, attack: 310, defense: 280, speed: 105 },
    starterAbilities: ['infinite-darkness'],
    starterPassives: ['shadow-veil', 'decay-aura', 'shadow-master', 'soul-drain'],
    visualTags: ['shadow', 'eternal', 'primordial'],
    lore: 'The darkness that existed before light, eternal and unchanging throughout all ages.',
  },
  {
    id: brandBasePetId('BASE-SHADOW-015'),
    name: 'Oblivion\'s Echo',
    family: PetFamily.SHADOW_VEIL,
    rarity: Rarity.MYTHIC,
    baseStats: { hp: 3950, attack: 320, defense: 290, speed: 103 },
    starterAbilities: ['echo-of-nothing'],
    starterPassives: ['soul-drain', 'shadow-master', 'decay-aura', 'shadow-veil'],
    visualTags: ['shadow', 'void', 'nothingness'],
    lore: 'The echo of oblivion itself, reminding all things of the void they came from.',
  },
];

// LUMINA - Light family (15 pets)
export const LUMINA_PETS: any[] = [
  // Basic
  {
    id: brandBasePetId('BASE-LUMINA-001'),
    name: 'Lightling',
    family: PetFamily.LUMINA,
    rarity: Rarity.BASIC,
    baseStats: { hp: 520, attack: 49, defense: 37, speed: 68 },
    starterAbilities: ['light-beam'],
    starterPassives: [],
    visualTags: ['light', 'bright', 'glowing'],
    lore: 'A small orb of pure light that spreads hope and warmth wherever it goes.',
  },
  {
    id: brandBasePetId('BASE-LUMINA-002'),
    name: 'Sunflare',
    family: PetFamily.LUMINA,
    rarity: Rarity.BASIC,
    baseStats: { hp: 535, attack: 48, defense: 38, speed: 66 },
    starterAbilities: ['solar-flare'],
    starterPassives: [],
    visualTags: ['light', 'sun', 'bright'],
    lore: 'A creature that embodies the brightness of the sun, burning with holy energy.',
  },
  {
    id: brandBasePetId('BASE-LUMINA-003'),
    name: 'Starseeker',
    family: PetFamily.LUMINA,
    rarity: Rarity.BASIC,
    baseStats: { hp: 545, attack: 50, defense: 39, speed: 69 },
    starterAbilities: ['stellar-guide'],
    starterPassives: [],
    visualTags: ['light', 'celestial', 'guiding'],
    lore: 'A creature that follows the stars, seeking enlightenment and guidance.',
  },
  {
    id: brandBasePetId('BASE-LUMINA-004'),
    name: 'Dawnbringer',
    family: PetFamily.LUMINA,
    rarity: Rarity.BASIC,
    baseStats: { hp: 515, attack: 51, defense: 36, speed: 71 },
    starterAbilities: ['dawn-strike'],
    starterPassives: [],
    visualTags: ['light', 'dawn', 'awakening'],
    lore: 'A herald of the new day, bringing light to the darkest places.',
  },
  {
    id: brandBasePetId('BASE-LUMINA-005'),
    name: 'Radiance Sprite',
    family: PetFamily.LUMINA,
    rarity: Rarity.BASIC,
    baseStats: { hp: 540, attack: 47, defense: 40, speed: 67 },
    starterAbilities: ['radiance-aura'],
    starterPassives: [],
    visualTags: ['light', 'sprite', 'shining'],
    lore: 'A magical creature of pure light that heals all around it with its radiance.',
  },
  // Rare
  {
    id: brandBasePetId('BASE-LUMINA-006'),
    name: 'Angelborn',
    family: PetFamily.LUMINA,
    rarity: Rarity.RARE,
    baseStats: { hp: 900, attack: 81, defense: 68, speed: 74 },
    starterAbilities: ['angel-blessing'],
    starterPassives: ['holy-aura'],
    visualTags: ['light', 'angel', 'divine'],
    lore: 'An angelic being of pure light that protects the innocent and heals the wounded.',
  },
  {
    id: brandBasePetId('BASE-LUMINA-007'),
    name: 'Solstice Guardian',
    family: PetFamily.LUMINA,
    rarity: Rarity.RARE,
    baseStats: { hp: 920, attack: 79, defense: 70, speed: 72 },
    starterAbilities: ['solstice-shield'],
    starterPassives: ['light-resonance'],
    visualTags: ['light', 'protector', 'eternal'],
    lore: 'A guardian of the eternal cycle of seasons, bringing balance and protection.',
  },
  {
    id: brandBasePetId('BASE-LUMINA-008'),
    name: 'Celestial Phoenix',
    family: PetFamily.LUMINA,
    rarity: Rarity.RARE,
    baseStats: { hp: 940, attack: 83, defense: 69, speed: 75 },
    starterAbilities: ['celestial-rebirth'],
    starterPassives: ['redemption-aura'],
    visualTags: ['light', 'phoenix', 'celestial'],
    lore: 'A phoenix of celestial light that brings renewal and redemption to all.',
  },
  // SR
  {
    id: brandBasePetId('BASE-LUMINA-009'),
    name: 'Solargod',
    family: PetFamily.LUMINA,
    rarity: Rarity.SR,
    baseStats: { hp: 1510, attack: 128, defense: 115, speed: 82 },
    starterAbilities: ['solar-judgment'],
    starterPassives: ['holy-aura', 'light-resonance'],
    visualTags: ['light', 'god', 'solar'],
    lore: 'A god of the sun wielding the power of a billion suns.',
  },
  {
    id: brandBasePetId('BASE-LUMINA-010'),
    name: 'Eternal Dawn',
    family: PetFamily.LUMINA,
    rarity: Rarity.SR,
    baseStats: { hp: 1490, attack: 130, defense: 113, speed: 84 },
    starterAbilities: ['eternal-light'],
    starterPassives: ['redemption-aura', 'light-resonance'],
    visualTags: ['light', 'eternal', 'dawn'],
    lore: 'The first light of creation itself, capable of piercing any darkness.',
  },
  {
    id: brandBasePetId('BASE-LUMINA-011'),
    name: 'Paradox Healer',
    family: PetFamily.LUMINA,
    rarity: Rarity.SR,
    baseStats: { hp: 1540, attack: 126, defense: 118, speed: 80 },
    starterAbilities: ['paradox-mend'],
    starterPassives: ['holy-aura', 'redemption-aura'],
    visualTags: ['light', 'healer', 'paradoxical'],
    lore: 'A healer that exists in contradiction, mending what cannot be broken.',
  },
  // Legendary
  {
    id: brandBasePetId('BASE-LUMINA-012'),
    name: 'Apollo Incarnate',
    family: PetFamily.LUMINA,
    rarity: Rarity.LEGENDARY,
    baseStats: { hp: 2400, attack: 188, defense: 180, speed: 88 },
    starterAbilities: ['apollo-blessing'],
    starterPassives: ['holy-aura', 'light-resonance', 'redemption-aura'],
    visualTags: ['light', 'god', 'perfect'],
    lore: 'The god of light and healing, bringing perfection and grace to all.',
  },
  {
    id: brandBasePetId('BASE-LUMINA-013'),
    name: 'Cosmic Light',
    family: PetFamily.LUMINA,
    rarity: Rarity.LEGENDARY,
    baseStats: { hp: 2350, attack: 192, defense: 175, speed: 90 },
    starterAbilities: ['cosmic-brilliance'],
    starterPassives: ['redemption-aura', 'light-resonance', 'holy-aura'],
    visualTags: ['light', 'cosmic', 'galactic'],
    lore: 'Light from the very stars themselves, ancient and infinite in power.',
  },
  // Mythic
  {
    id: brandBasePetId('BASE-LUMINA-014'),
    name: 'Eternal Radiance',
    family: PetFamily.LUMINA,
    rarity: Rarity.MYTHIC,
    baseStats: { hp: 3850, attack: 300, defense: 310, speed: 100 },
    starterAbilities: ['infinite-luminescence'],
    starterPassives: ['holy-aura', 'light-resonance', 'redemption-aura', 'divine-grace'],
    visualTags: ['light', 'eternal', 'infinite'],
    lore: 'The light that has always existed, unchanging and eternal, the source of all goodness.',
  },
  {
    id: brandBasePetId('BASE-LUMINA-015'),
    name: 'Creation\'s Spark',
    family: PetFamily.LUMINA,
    rarity: Rarity.MYTHIC,
    baseStats: { hp: 3950, attack: 310, defense: 300, speed: 105 },
    starterAbilities: ['creation-flash'],
    starterPassives: ['divine-grace', 'redemption-aura', 'light-resonance', 'holy-aura'],
    visualTags: ['light', 'creation', 'cosmic'],
    lore: 'The very spark of creation itself, capable of birthing new worlds with its light.',
  },
];

// STEEL_WORKS - Metal family (15 pets)
export const STEEL_WORKS_PETS: BasePet[] = [
  // Basic
  {
    id: brandBasePetId('BASE-STEEL-001'),
    name: 'Ironpup',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.BASIC,
    baseStats: { hp: 550, attack: 46, defense: 44, speed: 60 },
    starterAbilities: ['iron-bite'],
    starterPassives: [],
    visualTags: ['metal', 'steel', 'mechanical'],
    lore: 'A small metal creature with the loyalty of a dog and the strength of iron.',
  },
  {
    id: brandBasePetId('BASE-STEEL-002'),
    name: 'Cogling',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.BASIC,
    baseStats: { hp: 540, attack: 47, defense: 43, speed: 62 },
    starterAbilities: ['gear-grind'],
    starterPassives: [],
    visualTags: ['metal', 'mechanical', 'whirring'],
    lore: 'A small metal creature that spins and whirrs, powered by inner clockwork.',
  },
  {
    id: brandBasePetId('BASE-STEEL-003'),
    name: 'Brasskin',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.BASIC,
    baseStats: { hp: 560, attack: 48, defense: 45, speed: 61 },
    starterAbilities: ['brass-hammer'],
    starterPassives: [],
    visualTags: ['metal', 'brass', 'solid'],
    lore: 'A creature of solid brass that reflects light and truth.',
  },
  {
    id: brandBasePetId('BASE-STEEL-004'),
    name: 'Titanium Sprite',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.BASIC,
    baseStats: { hp: 535, attack: 49, defense: 42, speed: 63 },
    starterAbilities: ['titanium-strike'],
    starterPassives: [],
    visualTags: ['metal', 'titanium', 'light-but-strong'],
    lore: 'A tiny sprite made of ultralight titanium, fast and nearly unbreakable.',
  },
  {
    id: brandBasePetId('BASE-STEEL-005'),
    name: 'Silverling',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.BASIC,
    baseStats: { hp: 545, attack: 47, defense: 41, speed: 65 },
    starterAbilities: ['silver-beam'],
    starterPassives: [],
    visualTags: ['metal', 'silver', 'reflective'],
    lore: 'A creature of pure silver that reflects magic and light alike.',
  },
  // Rare
  {
    id: brandBasePetId('BASE-STEEL-006'),
    name: 'Ironclad Knight',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.RARE,
    baseStats: { hp: 950, attack: 77, defense: 77, speed: 66 },
    starterAbilities: ['knight-slash'],
    starterPassives: ['metal-body'],
    visualTags: ['metal', 'knight', 'armor'],
    lore: 'A knight forged from pure iron, standing eternal watch.',
  },
  {
    id: brandBasePetId('BASE-STEEL-007'),
    name: 'Gearmaster',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.RARE,
    baseStats: { hp: 930, attack: 76, defense: 76, speed: 68 },
    starterAbilities: ['gear-explosion'],
    starterPassives: ['mechanical-mind'],
    visualTags: ['metal', 'mechanical', 'master'],
    lore: 'A master engineer made of gears and springs, perfectly calibrated.',
  },
  {
    id: brandBasePetId('BASE-STEEL-008'),
    name: 'Platinum Sentinel',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.RARE,
    baseStats: { hp: 960, attack: 75, defense: 78, speed: 64 },
    starterAbilities: ['platinum-guard'],
    starterPassives: ['noble-metal'],
    visualTags: ['metal', 'platinum', 'sentinel'],
    lore: 'A sentinel of pure platinum, untarnished and eternal.',
  },
  // SR
  {
    id: brandBasePetId('BASE-STEEL-009'),
    name: 'Forge Master',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.SR,
    baseStats: { hp: 1580, attack: 125, defense: 128, speed: 76 },
    starterAbilities: ['forge-creation'],
    starterPassives: ['metal-body', 'mechanical-mind'],
    visualTags: ['metal', 'forge', 'creator'],
    lore: 'A master of forges who can create weapons and armor of legend.',
  },
  {
    id: brandBasePetId('BASE-STEEL-010'),
    name: 'Alloy Phoenix',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.SR,
    baseStats: { hp: 1560, attack: 128, defense: 126, speed: 78 },
    starterAbilities: ['alloy-rebirth'],
    starterPassives: ['noble-metal', 'metal-body'],
    visualTags: ['metal', 'phoenix', 'reborn'],
    lore: 'A phoenix of tempered alloy that rises from the ashes of battle.',
  },
  {
    id: brandBasePetId('BASE-STEEL-011'),
    name: 'Clockwork Titan',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.SR,
    baseStats: { hp: 1540, attack: 130, defense: 124, speed: 80 },
    starterAbilities: ['clockwork-march'],
    starterPassives: ['mechanical-mind', 'noble-metal'],
    visualTags: ['metal', 'clockwork', 'titan'],
    lore: 'A titan of perfect clockwork, marching with inexorable precision.',
  },
  // Legendary
  {
    id: brandBasePetId('BASE-STEEL-012'),
    name: 'Vulcan\'s Hammer',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.LEGENDARY,
    baseStats: { hp: 2450, attack: 182, defense: 185, speed: 84 },
    starterAbilities: ['vulcan-strike'],
    starterPassives: ['metal-body', 'mechanical-mind', 'noble-metal'],
    visualTags: ['metal', 'god', 'hammer'],
    lore: 'The hammer of Vulcan himself, capable of forging gods.',
  },
  {
    id: brandBasePetId('BASE-STEEL-013'),
    name: 'Mithril Golem',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.LEGENDARY,
    baseStats: { hp: 2500, attack: 188, defense: 190, speed: 82 },
    starterAbilities: ['mithril-armor'],
    starterPassives: ['noble-metal', 'metal-body', 'mechanical-mind'],
    visualTags: ['metal', 'mithril', 'legendary'],
    lore: 'A golem of legendary mithril, stronger than mountains, older than kingdoms.',
  },
  // Mythic
  {
    id: brandBasePetId('BASE-STEEL-014'),
    name: 'Eternal Forge',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.MYTHIC,
    baseStats: { hp: 3950, attack: 295, defense: 315, speed: 92 },
    starterAbilities: ['infinite-forging'],
    starterPassives: ['metal-body', 'mechanical-mind', 'noble-metal', 'perfect-alloy'],
    visualTags: ['metal', 'forge', 'eternal'],
    lore: 'The eternal forge itself given form, capable of creating anything.',
  },
  {
    id: brandBasePetId('BASE-STEEL-015'),
    name: 'Singularity Engine',
    family: PetFamily.STEEL_WORKS,
    rarity: Rarity.MYTHIC,
    baseStats: { hp: 4000, attack: 305, defense: 305, speed: 95 },
    starterAbilities: ['engine-collapse'],
    starterPassives: ['perfect-alloy', 'mechanical-mind', 'metal-body', 'noble-metal'],
    visualTags: ['metal', 'singularity', 'reality-warping'],
    lore: 'An engine containing a singularity, warping reality itself to its will.',
  },
];

// Combine all extended families
export const ALL_EXTENDED_BASE_PETS: BasePet[] = [
  ...SHADOW_VEIL_PETS,
  ...LUMINA_PETS,
  ...STEEL_WORKS_PETS,
];
