import { GeometrySchema } from '../generators/logic/GeometryLogic';

export class ObjRenderer {
    async render(schema: GeometrySchema): Promise<string> {
        let obj = `# Generated by Vibe Coding Geometry Generator\n`;
        obj += `# ID: ${schema.id}\n`;
        obj += `# Vertices: ${schema.vertices.length}\n`;
        obj += `# Faces: ${schema.faces.length}\n\n`;

        // Vertices
        for (const v of schema.vertices) {
            obj += `v ${v[0]} ${v[1]} ${v[2]}\n`;
        }

        obj += `\n`;

        // Faces
        // OBJ indices are 1-based
        for (const f of schema.faces) {
            const faceStr = f.map(idx => idx + 1).join(' ');
            obj += `f ${faceStr}\n`;
        }

        return obj;
    }
}
