const fs = require('fs-extra');
const path = require('path');

class PhaserBinder {
  constructor(registry) {
    this.registry = registry;
  }

  async generate(projectPath) {
    const assets = await this.registry.findByProject(path.basename(projectPath));
    
    const lines = [
      '// Auto-generated by Vibecoder Asset Pipeline',
      '// DO NOT EDIT MANUALLY',
      '',
      'export const Assets = {'
    ];

    const preloadLines = [];

    for (const asset of assets) {
      const safeName = asset.name.toUpperCase().replace(/\s+/g, '_');
      const relativePath = path.relative(path.join(projectPath, 'src'), asset.processedPath || '').replace(/\\/g, '/');
      
      lines.push(`  ${safeName}: '${relativePath}',`);
      
      if (asset.type === 'sprite') {
          preloadLines.push(`    scene.load.image(Assets.${safeName}, '${relativePath}');`);
      } else if (asset.type === 'sfx') {
          preloadLines.push(`    scene.load.audio(Assets.${safeName}, '${relativePath}');`);
      }
    }

    lines.push('};');
    lines.push('');
    lines.push('export function preloadAssets(scene: Phaser.Scene) {');
    lines.push(...preloadLines);
    lines.push('}');

    return lines.join('\n');
  }
}

module.exports = PhaserBinder;
